package enums;

/**
 * @author Kaelan
 */
enum abstract PropName(String) to String
{
	var TAG;
	var BLOODCOLOR;
	var SPECIES;
	var OBITUARY;
	var SEESOUND;
	var ACTIVESOUND;
	var DEATHSOUND;
	var HEALTH;
	var MONSTER;
	var RADIUS;
	var HEIGHT;
	var MASS;
	var SPEED;
	var PAINCHANCE;
	var MAXTARGETRANGE;
	var GIBHEALTH;
	var DAMAGEFACTOR;
	var DAMAGETYPE;
	var SCALE;
	var GAME;
	var SPAWNID;
	var WEAPONSELECTIONORDER;
	var WEAPONAMMOUSE;
	var WEAPONAMMOGIVE;
	var WEAPONAMMOTYPE;
	var ATTACKSOUND;
	var INVENTORYPICKUPMESSAGE;
	var INVENTORYAMOUNT;
	var INVENTORYMAXAMOUNT;
	var INVENTORYICON;
	var AMMOBACKPACKAMOUNT;
	var AMMOBACKPACKMAXAMOUNT;
	var PLAYERWEAPONSLOT;
}