package types;
import types.propvalues.PropData;

/**
 * ...
 * @author Kaelan
 */
class Actor 
{
	
	public var decoActor:Bool;
	
	public var name:String;
	public var inherits:String = "Actor";
	public var replaces:Null<String> = null;
	
	public var states:Array<DecoState>;
	public var properties:Array<PropData>;
	
	public function new(_name:String, _edNum:Int = 0, _decorate:Bool = true) 
	{
		decoActor = _decorate;
		
		name = _name;
		states = new Array();
		properties = new Array();
	}
	
	public function toZScriptActor():String
	{
		var info = '';
		info += 'Class ${name} : ${inherits}' + (replaces == null ? "\n" : ' replaces ${replaces}\n');
		info += '{\n';
		info += '\tDefault\n';
		info += '\t{\n';
		
		for (prop in properties)
		{
			info += '\t\t' + prop.toZScript() + '\n';
		}
		
		info += '\t}\n';
		info += '}\n';
		info += '//ZScript class generated by decoz at';
		
		return info;
	}
	
}